development:
  adapter: mysql2
  encoding: utf8
  database: adventure_store_development
  username: root
  socket: /tmp/mysql.sock
  host: 127.0.0.1
test:
  adapter: mysql2
  encoding: utf8
  database: adventure_store_test
  username: root
  socket: /tmp/mysql.sock
  host: 127.0.0.1



